export { default as Navbar } from "./Navbar";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Projects } from "./Projects";
export { default as Services } from "./Services";
export { default as HeroComp } from "./HeroComp";
export { default as Technologies } from "./Technologies";
export { default as Experience } from "./Experience";
